
# UNCOMMENT THIS TO RUN LOCALLY
# FROM node:18 As development
# WORKDIR /code
# COPY --chown=node:node package*.json package-lock.json .env ./
# RUN npm install
# COPY --chown=node:node . .
# USER node
